// Export nanny questions with explicit names to avoid conflicts
export {
  NANNY_MAIN_QUESTIONS,
  NANNY_CONDITIONAL_QUESTIONS,
  NANNY_STEP_CONFIGS,
  TOTAL_MAIN_QUESTIONS,
  type NannyFormData,
  getQuestion as getNannyQuestion,
  getNextDestination as getNannyNextDestination,
  getPrevDestination as getNannyPrevDestination,
  findResumePoint as findNannyResumePoint,
  calculateProgress as calculateNannyProgress,
  getMaritalStatusOptionsForGender,
  nannyStep1Questions,
  nannyStep1Config,
  nannyStep2Questions,
  nannyStep2Config,
  nannyStep3Questions,
  nannyStep3Config,
  nannyStep4Questions,
  nannyStep4Config,
  nannyStep5Questions,
  nannyStep5Config,
  nannyStep6Questions,
  nannyStep6Config,
  nannyStep7Questions,
  nannyStep7Config,
  nannyStep8Questions,
  nannyStep8Config,
  nannyStep9Questions,
  nannyStep9Config,
  nannyStep10Questions,
  nannyStep10Config,
} from './nanny-questions';

// Export family questions with explicit names to avoid conflicts
export {
  FAMILY_ALL_QUESTIONS,
  TOTAL_FAMILY_QUESTIONS,
  type FamilyFormData,
  getQuestion as getFamilyQuestion,
  getNextDestination as getFamilyNextDestination,
  getPrevDestination as getFamilyPrevDestination,
  findResumePoint as findFamilyResumePoint,
  calculateProgress as calculateFamilyProgress,
  getQuestionIndex as getFamilyQuestionIndex,
  getVisibleQuestions,
} from './family-questions';
